using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WorldEditor.Loaders.Classes;
using WorldEditor.Loaders.Data;

namespace WorldEditor.Loaders.Objetcs
{
    [D2OClass("Effect", "com.ankamagames.dofus.datacenter.effects", true), TableName("effects_templates")]
    public class EffectTemplate : IAutoGeneratedRecord
    {
        [PrimaryKey("Id")]
        public int Id { get; set; }

        public uint DescriptionId { get; set; }

        public int IconId { get; set; }

        public int Characteristic { get; set; }

        public uint Category { get; set; }

        public string Operator { get; set; }

        public bool UseDice { get; set; }

        public bool ForceMinMax { get; set; }

        public bool Boost { get; set; }

        public bool Active { get; set; }

        public bool ShowInSet { get; set; }

        public int BonusType { get; set; }

        public bool UseInFight { get; set; }

        public uint Priority { get; set; }
    }

    public class EffectTemplateRelator
    {
        public static string FetchQuery = "SELECT * FROM effects_templates";
    }
}
