using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using WorldEditor.Helpers.IO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WorldEditor.Loaders.Classes;
using WorldEditor.Loaders.Data;
using WorldEditor.Loaders.I18N;

namespace WorldEditor.Loaders.Objetcs
{
    [D2OClass("ItemSet", "com.ankamagames.dofus.datacenter.items", true), TableName("items_sets")]
    public sealed class ItemSetTemplate : IAutoGeneratedRecord, IObject
    {
        [PrimaryKey("Id")]
        public int Id { get; set; }

        public string ItemsCSV { get; set; }

        [I18NField]
        public uint NameId { get; set; }

        public bool BonusIsSecret { get; set; }

        public byte[] EffectsBin { get; set; }

        [Ignore]
        public string Name
        {
            get { return I18NDataManager.Instance.ReadText(NameId); }
        }

        public object GetD2oClass(object baseObj)
        {
            var result = new ItemSet();

            result.id = (uint)this.Id;
            result.items = this.ItemsCSV.FromCSV<uint>(",").ToList();
            result.nameId = this.NameId;
            result.bonusIsSecret = this.BonusIsSecret;
            result.effects = EffectsBin.ToObject<List<byte[]>>().Select(entry => entry.ToObject<List<EffectInstance>>()).ToList();
            
            return result;
        }
    }

    public class ItemSetTemplateRelator
    {
        public static string FetchQuery = "SELECT * FROM items_sets";
        public static string FetchById = "SELECT * FROM items_sets WHERE Id = @0";
    }
}