using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WorldEditor.Loaders.Classes;
using WorldEditor.Loaders.Data;
using WorldEditor.Loaders.I18N;
using WorldEditor.Loaders.Objetcs.Enums;

namespace WorldEditor.Loaders.Objetcs
{
    [D2OClass("ItemType", "com.ankamagames.dofus.datacenter.items", true), TableName("items_types")]
    public sealed class ItemTypeRecord : IAutoGeneratedRecord, IObject
    {
        [PrimaryKey("Id")]
        public int Id { get; set; }

        [Ignore]
        public ItemTypeEnum ItemType
        {
            get { return (ItemTypeEnum)Id; }
        }

        [Ignore]
        public ItemSuperTypeEnum SuperType
        {
            get { return (ItemSuperTypeEnum)SuperTypeId; }
        }

        [I18NField]
        public uint NameId { get; set; }

        public uint SuperTypeId { get; set; }

        public bool Plural { get; set; }

        public uint Gender { get; set; }

        public uint ZoneMinSize { get; set; }

        public uint ZoneSize { get; set; }

        public SpellShapeEnum ZoneShape { get; set; }

        public bool NeedUseConfirm { get; set; }

        [NullString]
        public string RawZone { get; set; }

        [Ignore]
        public string Name
        {
            get { return I18NDataManager.Instance.ReadText(NameId); }
        }

        public object GetD2oClass(object baseObj)
        {
            var result = new ItemType();
            var itemType = baseObj as ItemType;

            result.id = this.Id;
            result.nameId = this.NameId;
            result.gender = this.Gender;
            result.mimickable = false;
            //result.ne = this.NeedUseConfirm;
            result.plural = this.Plural;
            result.rawZone = this.RawZone;
            result.superTypeId = this.SuperTypeId;
            return result;
        }
    }

    public class ItemTypeRecordRelator
    {
        public static string FetchQuery = "SELECT * FROM items_types";
        public static string FetchById = "SELECT * FROM items_types WHERE Id=@0";
    }
}
