using Stump.Core.IO;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Companion {
    [TableName("companion_characteristics")]
    public class CompanionCharacteristicRecord : IAutoGeneratedRecord {
        private string _statPerLevelRange;
        private double[][] _statPerLevelRangeIds;

        [PrimaryKey("Id", false)]
        public int Id { get; set; }

        public int CaracId { get; set; }
        public int CompanionId { get; set; }
        public int Order { get; set; }

        public string StatPerLevelRange {
            get { return _statPerLevelRange; }
            set {
                _statPerLevelRange = value;
                _statPerLevelRangeIds = StatPerLevelRange.FromCSV("|", x => x.FromCSV<double>(","));
            }
        }

        [Ignore]
        public double[][] StatPerLevelRangeIds {
            get {
                double[][] arg_40_0;
                if ((arg_40_0 = _statPerLevelRangeIds) == null)
                    arg_40_0 = _statPerLevelRangeIds = StatPerLevelRange.FromCSV("|", x => x.FromCSV<double>(","));
                return arg_40_0;
            }
            set {
                _statPerLevelRangeIds = value;
                StatPerLevelRange = value.ToCSV("|", x => x.ToCSV(","));
            }
        }
    }
}