using Stump.DofusProtocol.D2oClasses;
using Stump.DofusProtocol.D2oClasses.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Symbols
{
	[D2OClass("EmblemSymbol", "com.ankamagames.dofus.datacenter.guild", true), TableName("symbol_emblems")]
	public class EmblemRecord : IAutoGeneratedRecord, IAssignedByD2O
	{
		[PrimaryKey(false)]
		public int Id
		{
			get;
			set;
		}
		public int IconId
		{
			get;
			set;
		}
		public int SkinId
		{
			get;
			set;
		}
		public int Order
		{
			get;
			set;
		}
		public int CategoryId
		{
			get;
			set;
		}
		public bool Colorizable
		{
			get;
			set;
		}
		public void AssignFields(object d2oObject)
		{
			EmblemSymbol emblemSymbol = (EmblemSymbol)d2oObject;
			this.Id = emblemSymbol.id;
			this.IconId = emblemSymbol.iconId;
			this.SkinId = emblemSymbol.skinId;
			this.Order = emblemSymbol.order;
			this.CategoryId = emblemSymbol.categoryId;
			this.Colorizable = emblemSymbol.colorizable;
		}
	}
}
