using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using System;

namespace Database.Dopeul
{
    [TableName("characters_dopeul")]
    public class DopeulRecord : IAutoGeneratedRecord
    {
        [PrimaryKey("Id")] // Idiota! ._.
        public int Id { get; set; }
        public int CharacterId { get; set; }
        public int DopeulId { get; set; }
        public DateTime Time { get; set; }
        public string Ip { get; set; }
        [Ignore]
        public bool IsNew { get; set; }
        [Ignore]
        public bool IsUpdated { get; set; }
    }
}
