using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Database
{
    [TableName("character_UtilisationToken")]
    public class UtilisationTokenRecord : IAutoGeneratedRecord
    {
        [PrimaryKey("Id", true)]
        public int Id
        {
            get;
            set;
        }
        public string OwnerName
        {
            get;
            set;
        }
        public int OwnerId
        {
            get;
            set;
        }
        public int TokenAvantAchat
        {
            get;
            set;
        }
        public int TokenApreAchat
        {
            get;
            set;
        }
        public string TransactionType
        {
            get;
            set;
        }
        public int itemId
        {
            get;
            set;
        }
        public int ItemStack
        {
            get;
            set;
        }
        public string TokenName
        {
            get;
            set;
        }
        public DateTime Time
        {
            get;
            set;
        }
    }
}
