using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using System;

namespace Stump.Server.WorldServer.Database.Alliances
{
    [TableName("alliances")]
    public class AllianceRecord : IAutoGeneratedRecord
    {
        // FIELDS

        // PROPERTIES
        [PrimaryKey("Id", false)]
        public int Id { get; set; }
        [Ignore]
        public bool IsNew { get; set; }
        public int Owner { get; set; }
        public string Name { get; set; }
        public string Tag { get; set; }
        public DateTime CreationDate { get; set; }
        public short EmblemBackgroundShape { get; set; }
        public int EmblemBackgroundColor { get; set; }
        public short EmblemForegroundShape { get; set; }
        public int EmblemForegroundColor { get; set; }

        // CONSTRUCTORS

        // METHODS
    }
}
