using Stump.Core.Reflection;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using Stump.Server.WorldServer.Game.Maps;

namespace Stump.Server.WorldServer.Database.Monsters
{
	[TableName("monsters_disable_spawns")]
	public class MonsterDisableSpawn : IAutoGeneratedRecord
	{
		private SubArea m_subArea;
		[PrimaryKey("Id", true)]
		public int Id
		{
			get;
			set;
		}
		public int? SubAreaId
		{
			get;
			set;
		}
		[Ignore]
		public SubArea SubArea
		{
			get
			{
				SubArea result;
				if (!this.SubAreaId.HasValue)
				{
					result = null;
				}
				else
				{
					SubArea arg_3F_0;
					if ((arg_3F_0 = this.m_subArea) == null)
					{
                        arg_3F_0 = (this.m_subArea = Singleton<Game.World>.Instance.GetSubArea(this.SubAreaId.Value));
					}
					result = arg_3F_0;
				}
				return result;
			}
			set
			{
				this.m_subArea = value;
				if (value == null)
				{
					this.SubAreaId = null;
				}
				else
				{
					this.SubAreaId = new int?(value.Id);
				}
			}
		}
		public int MonsterId
		{
			get;
			set;
		}
	}
}
