using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;

namespace Stump.Server.WorldServer.Database.Monsters
{
    [TableName("monster_spells_custom")]
    public class MonsterSpellCustomRecord : IAutoGeneratedRecord
    {
        public int Id { get; set; }
        public int SpellId { get; set; }
        public int MonsterId { get; set; }
        public bool IsControlable { get; set; }
        public string Notes { get; set; }
    }
}
